#!/usr/bin/env python3
"""Generate man/undatum.1 from the Typer command tree."""

from __future__ import annotations

import argparse
from datetime import date
from pathlib import Path

from typer.main import get_command

from undatum import __version__
from undatum.core import app

ROOT = Path(__file__).resolve().parents[1]
DEFAULT_OUTPUT = ROOT / "man" / "undatum.1"


def _groff(text: str) -> str:
    escaped = text.replace("\\", "\\\\").replace("-", "\\-")
    if escaped.startswith("."):
        return "\\&" + escaped
    return escaped


def _collect_commands(click_cmd, ctx, prefix: str = "") -> list[tuple[str, str]]:
    rows: list[tuple[str, str]] = []
    for name in click_cmd.list_commands(ctx):
        child = click_cmd.get_command(ctx, name)
        if child is None:
            continue
        full = f"{prefix}{name}" if not prefix else f"{prefix} {name}"
        summary = (child.get_short_help_str(limit=88) or "").strip()
        rows.append((full, summary))
        if getattr(child, "list_commands", None):
            child_ctx = child.make_context(name, [], parent=ctx, resilient_parsing=True)
            rows.extend(_collect_commands(child, child_ctx, full))
    return rows


def render_manpage() -> str:
    """Return groff source for undatum(1)."""
    click_app = get_command(app)
    ctx = click_app.make_context("undatum", [], resilient_parsing=True)
    commands = _collect_commands(click_app, ctx)
    month_year = date.today().strftime("%B %Y")
    lines = [
        '.\\" Generated by scripts/generate_manpage.py. Do not edit by hand.',
        f'.TH UNDATUM 1 "{month_year}" "undatum {__version__}" "User Commands"',
        ".SH NAME",
        "undatum \\- command\\-line tool for data processing and analysis",
        ".SH SYNOPSIS",
        ".B undatum",
        "[\\fIOPTIONS\\fR] \\fICOMMAND\\fR [\\fIARGS\\fR]...",
        ".br",
        ".B data",
        "[\\fIOPTIONS\\fR] \\fICOMMAND\\fR [\\fIARGS\\fR]...",
        ".SH DESCRIPTION",
        "undatum converts, validates, queries, and documents tabular and record data",
        "across CSV, JSON Lines, Parquet, BSON, Excel, and many other formats.",
        "Processing is streaming where possible. The",
        ".B data",
        "command is an alias for",
        ".BR undatum .",
        ".SH OPTIONS",
        ".TP",
        ".B \\-\\-version",
        "Print the undatum version and exit.",
        ".TP",
        ".B \\-\\-install\\-completion",
        "Install shell completion for the current shell.",
        ".TP",
        ".B \\-\\-help",
        "Show help for the command or subcommand.",
        ".SH COMMANDS",
    ]
    for name, summary in commands:
        lines.append(".TP")
        lines.append(f".B {_groff(name)}")
        lines.append(_groff(summary) if summary else "See undatum " + _groff(name) + " \\-\\-help.")
    lines.extend(
        [
            ".SH FILES",
            ".TP",
            ".I undatum.yaml",
            "Project configuration in the current directory (AI settings and CLI defaults).",
            ".TP",
            ".I ~/.undatum/config.yaml",
            "User\\-wide configuration. Project file overrides this file.",
            ".SH ENVIRONMENT",
            ".TP",
            ".B UNDATUM_ENGINE",
            "Default processing engine (auto, duckdb, python/iterable).",
            ".TP",
            ".B UNDATUM_THREADS",
            "Default worker process count for Python\\-engine parallelism.",
            ".TP",
            ".B UNDATUM_PROGRESS",
            "Default progress\\-bar setting (true/false).",
            ".TP",
            ".B UNDATUM_ENCODING",
            "Default text encoding.",
            ".TP",
            ".B UNDATUM_DELIMITER",
            "Default CSV delimiter. Omit to keep auto\\-detection.",
            ".TP",
            ".B UNDATUM_QUOTECHAR",
            "Default CSV quote character. Omit to keep iterabledata default '\"'.",
            ".TP",
            ".B UNDATUM_FORMAT_OUT",
            "Default analysis output format (for example json).",
            ".TP",
            ".B UNDATUM_API_KEY",
            "Optional API key for the read\\-only Data API and undatum web.",
            ".SH EXIT STATUS",
            ".TP",
            ".B 0",
            "Success.",
            ".TP",
            ".B 1",
            "User error (missing file, invalid format or parameters).",
            ".TP",
            ".B 2",
            "Configuration or missing optional dependency.",
            ".TP",
            ".B 3",
            "Permission or database/system error.",
            ".SH SEE ALSO",
            "Full documentation: https://github.com/datacoon/undatum",
            ".br",
            "Run",
            ".B undatum COMMAND \\-\\-help",
            "for command\\-specific options.",
            ".br",
            "Inspect resolved CLI defaults with",
            '.BR undatum " config show".',
        ]
    )
    return "\n".join(lines) + "\n"


def main(argv: list[str] | None = None) -> int:
    parser = argparse.ArgumentParser(description="Generate the undatum(1) man page.")
    parser.add_argument(
        "-o",
        "--output",
        type=Path,
        default=DEFAULT_OUTPUT,
        help="Output path (default: man/undatum.1)",
    )
    args = parser.parse_args(argv)
    args.output.parent.mkdir(parents=True, exist_ok=True)
    args.output.write_text(render_manpage(), encoding="utf-8")
    print(args.output)
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
